# Generated by Django 4.2.4 on 2023-10-12 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial_squashed_0007_alter_orderitem_order_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='extra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/image', validators=[store.validators.validate_file_size]),
        ),
    ]
